name: Deploy to FTP
         
on:
  push:
    branches:
      - main  # or any branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
            
      with:
        server: cafe33.cz
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Directory to upload
        server-dir: /tmp/test/  # Remote directory
